version: 2
jobs:
  build:
    working_directory: /interview_manager
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            touch .env
            apk add --no-cache py-pip=9.0.0-r1
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            cd app && python manage.py test"
