version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            touch .env
            echo "S3_KEY=$S3_KEY" >> .env
            echo "S3_BUCKET=$S3_BUCKET" >> .env
            echo "S3_SECRET=$S3_SECRET" >> .env
            echo "DEFAULT_CLIENT_HOST=http://localhost:4200" >> .env
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run app bash -c "cd app && python manage.py test"

      - deploy:
          name: 'Deploy the new image'
          command: |
            pip install fabric3 fabtools
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            fab docker_deploy
