version: 2
jobs:
  build:
    working_directory: /interview_manager
    docker:
      machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            touch .env
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run app bash -c "cd app && python manage.py test"
