version: '3'

services:
  app:
    image: vsokoltsov/interview360
    command: bash -c "python3 app/manage.py migrate && cd app && gunicorn app.wsgi:application -b 0.0.0.0:8000"
    expose:
      - '8000'
    env_file: ./.env
    enviroment:
      - DJANGO_DEFAULT_ENV=production
    depends_on:
      - rabbit

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:8000"
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file: ./.env
    ports:
      - "5672:5672"
      - "15672:15672"
