version: '3'

services:
  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
  web:
    build: .
    command: python3 app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/interview360
    ports:
      - "8000:8000"
    depends_on:
      - db
      
volumes:
  database:
