version: '3'

services:
  db:
    container_name: database
    image: postgres

  app:
    container_name: interview360
    build: .
    command: python3 app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/interview360
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    links:
      - celery_worker
    depends_on:
      - db
      - elasticsearch
      - rabbit

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    links:
      - kibana
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
      - "5601:5601"

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file:
      - ./.env
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    container_name: 'celery_worker'
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A app.app worker -l INFO"
    volumes:
      - .:/interview360
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=app.app.settings
    links:
      - rabbit
    depends_on:
      - rabbit
  #
  # celery_beat:
  #   container_name: 'celery_beat'
  #   build: .
  #   command: 'python -m celery -A app/app beat --pidfile= -l debug'
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - app

volumes:
  database:
