version: '3'

services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: 'interview_manager'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    image: vsokoltsov/interview360
    command: bash -c "python3 app/manage.py migrate && cd app && gunicorn app.wsgi:application -b 0.0.0.0:8000"
    expose:
      - '8000'
    env_file: ./.env
    depends_on:
      - db
      - elasticsearch
      - rabbit

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    links:
      - kibana
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
      - "5601:5601"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:8000"
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file: ./.env
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pg_data:
