version: '3'

services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: 'interview_manager'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    image: vsokoltsov/interview360
    container_name: interview360
    build: .
    command: bash -c "python3 app/manage.py migrate && cd app && gunicorn app.wsgi:application -b 0.0.0.0"
    volumes:
      - .:/interview360
    ports:
      - '8000:8000'
    env_file: ./.env
    links:
      - celery_worker
      - celery_beat
    depends_on:
      - db
      - elasticsearch
      - rabbit

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
      - "80:8000"
    volumes:
      - .:/interview360
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    links:
      - kibana
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
      - "5601:5601"

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file: ./.env
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    container_name: 'celery_worker'
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A app.app worker -l INFO"
    volumes:
      - .:/interview360
    env_file: ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=app.app.settings
    links:
      - rabbit
    depends_on:
      - rabbit

  celery_beat:
    container_name: 'celery_beat'
    build:
      context: .
      dockerfile: Dockerfile
    command: 'celery -A app.app beat -l debug'
    volumes:
      - .:/interview360
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=app.app.settings
    links:
      - rabbit
    depends_on:
      - rabbit

volumes:
  pg_data:
