- name: Load kibana package
  become: yes
  get_url:
    url: "{{ kibana_url }}"
    dest: "/root/{{ kibana_package_name }}"

- name: Check sha1sum for kibana package
  shell: "sha1sum {{ kibana_package_name }}"

- name: Install kibana
  yum:
    name: "{{ kibana_package_name }}"

- name: Start and enable kibana service
  service:
    name: kibana
    state: restarted
  become: true
