---
- name: install python 2
  raw: test -e /usr/bin/python || (yum -y update && yum install -y python-minimal)
  become: true

# - name: 'update yum'
#   yum: update_cache=yes
#   become: true

- name: 'install dependencies'
  yum: name="{{ item }}" state=present update_cache=yes
  with_items:
    - 'gcc'
    - 'gcc-c++'
    - 'make'
    - 'git'
    - 'patch'
    - 'openssl-devel'
    - 'zlib-devel'
    - 'readline-devel'
    - 'sqlite-devel'
    - 'bzip2-devel'
    - 'nginx'
    - 'wget'

- name: Update all packages to the latest version
  yum:
    name: '*'
    state: latest
  become: true
